apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        owner: armanabr
    spec:
      containers:
        - name: eureka-server
          image: armanabr/eureka-server:0.0.3
          ports:
            - name: eus-port
              containerPort: 8761
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: eus-port
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: eus-port
            initialDelaySeconds: 20
            periodSeconds: 3