apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        owner: armanabr
    spec:
      containers:
        - name: eureka-server
          image: armanabr/eureka-server:0.0.2.3
          ports:
            - containerPort: 8761