apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: k8s-microservice-song-project
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - protocol: "TCP"
      port: 8761 # Port exposed by the service within the cluster
      targetPort: 8761 # Port on which your application is running in the pods
      nodePort: 30003