apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-service-db-pvc
  namespace: k8s-microservice-song-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual