apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: api-gateway
        owner: armanabr
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.container.portName }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.container.portName }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
      initContainers:
        - name: init-eureka-server
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup eureka-server.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for eureka-server; sleep 2; done" ]
      restartPolicy: Always