image:
  repository: armanabr/eureka-server
  tag: 0.0.3
replicaCount: 1
container:
  port: 8761
  portName: eus-port
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 3
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 3
service:
  ports:
    port: 8761
    targetPort: 8761
    nodePort: 30003