image:
  repository: armanabr/api-gateway
  tag: 0.0.3
replicaCount: 1
container:
  port: 8080
  portName: apig-port
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 3
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 3
service:
  ports:
    port: 8080
    targetPort: 8080
    nodePort: 30001