apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-microservice-song-project
spec:
  selector:
    app: song-service
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.ports.port }} # Port exposed by the service within the cluster
      targetPort: {{ .Values.service.ports.targetPort }} # Port on which your application is running in the pods