apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: config-server
        owner: armanabr
    spec:
      containers:
        - name: config-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.container.portName }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.container.portName }}
            initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.container.livenessProbe.periodSeconds }}