apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-pg-db-config
  namespace: k8s-microservice-song-project
data:
  RESOURCE_SERVICE_SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-resource-service:5432/resource-service-db
  RESOURCE_SERVICE_SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
  RESOURCE_SERVICE_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect