apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
        owner: armanabr
    spec:
      containers:
        - name: api-gateway
          image: armanabr/api-gateway:0.0.2.2
          ports:
            - containerPort: 8080