apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: k8s-microservice-song-project
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: "TCP"
      port: 8080 # Port exposed by the service within the cluster
      targetPort: 8080 # Port on which your application is running in the pods
      nodePort: 30001