server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true