apiVersion: v1
kind: Secret
metadata:
  name: song-service-secrets
  namespace: k8s-microservice-song-project
  labels:
    app: song-service
type: Opaque
data:
  SONG_SERVICE_SPRING_DATASOURCE_USERNAME: dXNlcg==
  SONG_SERVICE_SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=