apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-microservice-song-project
spec:
  type: NodePort
  selector:
    app: song-service-pod
  ports:
    - protocol: "TCP"
      port: 8081 # Port exposed by the service within the cluster
      targetPort: 8081 # Port on which your application is running in the pods
      nodePort: 30005