apiVersion: v1
kind: Secret
metadata:
  name: song-service-secrets
  namespace: k8s-microservice-song-project
  labels:
    app: song-service
type: Opaque
data:
  SONG_SERVICE_SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc29uZy1zZXJ2aWNlLWRiOjU0MzIvc29uZy1zZXJ2aWNlLWRi
  SONG_SERVICE_SPRING_DATASOURCE_USERNAME: dXNlcg==
  SONG_SERVICE_SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  SONG_SERVICE_SPRING_DATASOURCE_DRIVER_CLASS: b3JnLnBvc3RncmVzcWwuRHJpdmVy
  SONG_SERVICE_HIBERNATE_DIALECT: b3JnLmhpYmVybmF0ZS5kaWFsZWN0LlBvc3RncmVTUUxEaWFsZWN0