apiVersion: v1
kind: Secret
metadata:
  name: postgres-resource-service-db-secrets
  namespace: k8s-microservice-song-project
  labels:
    app: postgres-resource-service-db
type: Opaque
data:
  POSTGRES_DB: cmVzb3VyY2Utc2VydmljZS1kYg==
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=