apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: k8s-microservice-song-project
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
        owner: armanabr
    spec:
      containers:
        - name: config-server
          image: armanabr/config-server:0.0.3
          ports:
            - name: confs-port
              containerPort: 8888
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: confs-port
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: confs-port
            initialDelaySeconds: 10
            periodSeconds: 3